language: cpp

sudo: required

compiler:
  - gcc-4.8

addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - cmake

script:
  - $CC --version
  - cd build
  - cmake .. -DANKI_BUILD_TOOLS=OFF
  - make -j 2

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux


