language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - cmake

script:
  - cd build
  - cmake .. -DANKI_BUILD_TOOLS=OFF

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux


