# Linux build configuration for Travis

language: cpp
sudo: false
dist: trusty
os: linux

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Debug EXTRA_CHECKS=ON TRACE=ON CXX=g++-5 CC=gcc-5
  - BUILD_TYPE=Release EXTRA_CHECKS=OFF TRACE=OFF CXX=g++-5 CC=gcc-5
  - BUILD_TYPE=Debug EXTRA_CHECKS=ON TRACE=ON CXX=clang++-3.5 CC=clang-3.5
  - BUILD_TYPE=Release EXTRA_CHECKS=OFF TRACE=OFF CXX=clang++-3.5 CC=clang-3.5

cache:
  apt: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:jonathonf/llvm'
    packages:
      - cmake
      - g++-5
      - clang-3.5

script:
  - mkdir build 
  - cd build
  - $CC --version
  - $CXX --version
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DANKI_EXTRA_CHECKS=${EXTRA_CHECKS} -DANKI_BUILD_TOOLS=ON -DANKI_BUILD_TESTS=ON -DANKI_ENABLE_TRACE=${TRACE}
  - make -j 2

branches:
  only:
    - master

notifications:
  email: false
