language: cpp

sudo: required

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"

script:
  - echo `$CC --version`
  - cd build
  - cmake .. -DANKI_BUILD_TOOLS=OFF
  - make -j 2

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux


