language: cpp

sudo: required

compiler:
  - gcc

addons:
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
      - cmake

script:
  - cd build
  - cmake .. -DANKI_BUILD_TOOLS=OFF -DCMAKE_CXX_COMPILER=`which g++-4.8` -DCMAKE_C_COMPILER=`which gcc-4.8`
  - make -j 2

branches:
  only:
    - master

notifications:
  email: false

os:
  - linux


