# Linux build configuration for Travis

language: cpp
sudo: false
dist: trusty
os: linux

compiler:
  - gcc
  - clang

env:
  - OPTIMIZE=ON TRACE=ON
  - OPTIMIZE=OFF TRACE=OFF

cache:
  apt: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - cmake
      - g++-4.9

before_install:
  # Set the newer gcc on Linux
  - export CXX="g++-4.9"
  - export CC="gcc-4.9"

script:
  - mkdir build 
  - cd build
  - cmake .. -DANKI_OPTIMIZE=${OPTIMIZE} -DANKI_DEBUG=${OPTIMIZE} -DANKI_DEBUG_SYMBOLS=OFF -DANKI_BUILD_TOOLS=ON -DANKI_BUILD_TESTS=ON -DANKI_ENABLE_TRACE=${TRACE}
  - make

branches:
  only:
    - master

notifications:
  email: false

